spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  profiles:
    include: jwt

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true